/**
 * Maps a player's `nationality` (API-Football's free-text country name,
 * already synced and stored verbatim on `players.nationality` — see
 * `src/lib/football-providers/api-football/adapter.ts` and
 * `src/lib/football-ingestion/sync-players.ts`) to a renderable circular
 * flag image. Pure and static: country name → ISO 3166-1 alpha-2 code
 * (plus the 4 genuine UK home-nation football codes, gb-eng/gb-sct/
 * gb-wls/gb-nir) is fixed, universal knowledge, not provider-specific
 * data that needs its own sync step or database column — no migration,
 * no new ingestion code (Pass 10.5C.5: see this pass's own report for why
 * that was the deliberate choice over adding a `country_code`/`flag_url`
 * column and a new API-Football "countries" sync).
 *
 * Deliberately NOT restricted to the Big Five leagues' most common
 * nationalities — every country this data set below covers gets a flag,
 * so a nationality's absence here is a gap to fill, not an intentional
 * cutoff.
 *
 * Flag artwork comes from flagcdn.com (a free, dedicated flag CDN, no API
 * key required, serving SVG) rather than API-Football's own media host.
 * API-Football's media URLs are meant for use within an authenticated API
 * session (server-side ingestion, this app's existing and only use of
 * it) — hotlinking them directly from every end user's own browser is a
 * materially different usage this pass can't verify is within the
 * provider's terms, so a provider-neutral, purpose-built flag CDN is the
 * "technically appropriate" choice the brief itself anticipated might be
 * necessary. The country NAMES below (the actual normalized data this
 * maps from) still come entirely from API-Football via Eleven's existing
 * sync — only the flag ARTWORK is sourced elsewhere.
 */

const COUNTRY_NAME_TO_FLAG_CODE: Record<string, string> = {
  "Afghanistan": "af",
  "Albania": "al",
  "Algeria": "dz",
  "American Samoa": "as",
  "Andorra": "ad",
  "Angola": "ao",
  "Anguilla": "ai",
  "Antarctica": "aq",
  "Antigua and Barbuda": "ag",
  "Argentina": "ar",
  "Armenia": "am",
  "Aruba": "aw",
  "Australia": "au",
  "Austria": "at",
  "Azerbaijan": "az",
  "Bahamas": "bs",
  "Bahrain": "bh",
  "Bangladesh": "bd",
  "Barbados": "bb",
  "Belarus": "by",
  "Belgium": "be",
  "Belize": "bz",
  "Benin": "bj",
  "Bermuda": "bm",
  "Bhutan": "bt",
  "Bolivia": "bo",
  "Bosnia": "ba",
  "Bosnia and Herzegovina": "ba",
  "Botswana": "bw",
  "Bouvet Island": "bv",
  "Brazil": "br",
  "British Indian Ocean Territory": "io",
  "British Virgin Islands": "vg",
  "Brunei": "bn",
  "Bulgaria": "bg",
  "Burkina Faso": "bf",
  "Burma": "mm",
  "Burundi": "bi",
  "Cabo Verde": "cv",
  "Cambodia": "kh",
  "Cameroon": "cm",
  "Canada": "ca",
  "Cape Verde": "cv",
  "Caribbean Netherlands": "bq",
  "Cayman Islands": "ky",
  "Central African Republic": "cf",
  "Chad": "td",
  "Chile": "cl",
  "China": "cn",
  "Chinese Taipei": "tw",
  "Christmas Island": "cx",
  "Cocos (Keeling) Islands": "cc",
  "Colombia": "co",
  "Comoros": "km",
  "Congo": "cg",
  "Congo DR": "cd",
  "Cook Islands": "ck",
  "Costa Rica": "cr",
  "Croatia": "hr",
  "Cuba": "cu",
  "Curacao": "cw",
  "Curaçao": "cw",
  "Cyprus": "cy",
  "Czech Republic": "cz",
  "Czechia": "cz",
  "Côte d'Ivoire (Ivory Coast)": "ci",
  "DR Congo": "cd",
  "DRC": "cd",
  "Denmark": "dk",
  "Djibouti": "dj",
  "Dominica": "dm",
  "Dominican Republic": "do",
  "Ecuador": "ec",
  "Egypt": "eg",
  "El Salvador": "sv",
  "England": "gb-eng",
  "Equatorial Guinea": "gq",
  "Eritrea": "er",
  "Estonia": "ee",
  "Eswatini": "sz",
  "Eswatini (Swaziland)": "sz",
  "Ethiopia": "et",
  "Falkland Islands": "fk",
  "Faroe Islands": "fo",
  "Fiji": "fj",
  "Finland": "fi",
  "France": "fr",
  "French Guiana": "gf",
  "French Polynesia": "pf",
  "French Southern and Antarctic Lands": "tf",
  "Gabon": "ga",
  "Gambia": "gm",
  "Georgia": "ge",
  "Germany": "de",
  "Ghana": "gh",
  "Gibraltar": "gi",
  "Greece": "gr",
  "Greenland": "gl",
  "Grenada": "gd",
  "Guadeloupe": "gp",
  "Guam": "gu",
  "Guatemala": "gt",
  "Guernsey": "gg",
  "Guinea": "gn",
  "Guinea-Bissau": "gw",
  "Guyana": "gy",
  "Haiti": "ht",
  "Heard Island and McDonald Islands": "hm",
  "Honduras": "hn",
  "Hong Kong": "hk",
  "Hungary": "hu",
  "Iceland": "is",
  "India": "in",
  "Indonesia": "id",
  "Iran": "ir",
  "Iraq": "iq",
  "Ireland": "ie",
  "Isle of Man": "im",
  "Israel": "il",
  "Italy": "it",
  "Ivory Coast": "ci",
  "Jamaica": "jm",
  "Japan": "jp",
  "Jersey": "je",
  "Jordan": "jo",
  "Kazakhstan": "kz",
  "Kenya": "ke",
  "Kiribati": "ki",
  "Korea DPR": "kp",
  "Korea Republic": "kr",
  "Kosovo": "xk",
  "Kuwait": "kw",
  "Kyrgyzstan": "kg",
  "Laos": "la",
  "Latvia": "lv",
  "Lebanon": "lb",
  "Lesotho": "ls",
  "Liberia": "lr",
  "Libya": "ly",
  "Liechtenstein": "li",
  "Lithuania": "lt",
  "Luxembourg": "lu",
  "Macau": "mo",
  "Macedonia": "mk",
  "Madagascar": "mg",
  "Malawi": "mw",
  "Malaysia": "my",
  "Maldives": "mv",
  "Mali": "ml",
  "Malta": "mt",
  "Marshall Islands": "mh",
  "Martinique": "mq",
  "Mauritania": "mr",
  "Mauritius": "mu",
  "Mayotte": "yt",
  "Mexico": "mx",
  "Micronesia": "fm",
  "Moldova": "md",
  "Monaco": "mc",
  "Mongolia": "mn",
  "Montenegro": "me",
  "Montserrat": "ms",
  "Morocco": "ma",
  "Mozambique": "mz",
  "Myanmar": "mm",
  "Namibia": "na",
  "Nauru": "nr",
  "Nepal": "np",
  "Netherlands": "nl",
  "New Caledonia": "nc",
  "New Zealand": "nz",
  "Nicaragua": "ni",
  "Niger": "ne",
  "Nigeria": "ng",
  "Niue": "nu",
  "Norfolk Island": "nf",
  "North Korea": "kp",
  "North Macedonia": "mk",
  "Northern Ireland": "gb-nir",
  "Northern Mariana Islands": "mp",
  "Norway": "no",
  "Oman": "om",
  "Pakistan": "pk",
  "Palau": "pw",
  "Palestine": "ps",
  "Panama": "pa",
  "Papua New Guinea": "pg",
  "Paraguay": "py",
  "Peru": "pe",
  "Philippines": "ph",
  "Pitcairn Islands": "pn",
  "Poland": "pl",
  "Portugal": "pt",
  "Puerto Rico": "pr",
  "Qatar": "qa",
  "Republic of Ireland": "ie",
  "Republic of the Congo": "cg",
  "Romania": "ro",
  "Russia": "ru",
  "Rwanda": "rw",
  "Réunion": "re",
  "Saint Barthélemy": "bl",
  "Saint Helena, Ascension and Tristan da Cunha": "sh",
  "Saint Kitts and Nevis": "kn",
  "Saint Lucia": "lc",
  "Saint Martin": "mf",
  "Saint Pierre and Miquelon": "pm",
  "Saint Vincent and the Grenadines": "vc",
  "Samoa": "ws",
  "San Marino": "sm",
  "Saudi Arabia": "sa",
  "Scotland": "gb-sct",
  "Senegal": "sn",
  "Serbia": "rs",
  "Seychelles": "sc",
  "Sierra Leone": "sl",
  "Singapore": "sg",
  "Sint Maarten": "sx",
  "Slovakia": "sk",
  "Slovenia": "si",
  "Solomon Islands": "sb",
  "Somalia": "so",
  "South Africa": "za",
  "South Georgia": "gs",
  "South Korea": "kr",
  "South Sudan": "ss",
  "Spain": "es",
  "Sri Lanka": "lk",
  "St Kitts and Nevis": "kn",
  "Sudan": "sd",
  "Suriname": "sr",
  "Svalbard and Jan Mayen": "sj",
  "Swaziland": "sz",
  "Sweden": "se",
  "Switzerland": "ch",
  "Syria": "sy",
  "São Tomé and Príncipe": "st",
  "Taiwan": "tw",
  "Tajikistan": "tj",
  "Tanzania": "tz",
  "Thailand": "th",
  "Timor-Leste": "tl",
  "Togo": "tg",
  "Tokelau": "tk",
  "Tonga": "to",
  "Trinidad and Tobago": "tt",
  "Tunisia": "tn",
  "Turkey": "tr",
  "Turkmenistan": "tm",
  "Turks and Caicos Islands": "tc",
  "Tuvalu": "tv",
  "UAE": "ae",
  "USA": "us",
  "Uganda": "ug",
  "Ukraine": "ua",
  "United Arab Emirates": "ae",
  "United Kingdom": "gb",
  "United States": "us",
  "United States Minor Outlying Islands": "um",
  "United States Virgin Islands": "vi",
  "Uruguay": "uy",
  "Uzbekistan": "uz",
  "Vanuatu": "vu",
  "Vatican City": "va",
  "Vatican City (Holy See)": "va",
  "Venezuela": "ve",
  "Vietnam": "vn",
  "Wales": "gb-wls",
  "Wallis and Futuna": "wf",
  "Western Sahara": "eh",
  "Yemen": "ye",
  "Zambia": "zm",
  "Zimbabwe": "zw",
  "Åland Islands": "ax",
};

/** The flagcdn.com code for a nationality string, or `null` if it has no known mapping. Exported for testing; prefer `flagUrlForNationality` elsewhere. */
export function flagCodeForNationality(nationality: string | null | undefined): string | null {
  if (!nationality) return null;
  return COUNTRY_NAME_TO_FLAG_CODE[nationality.trim()] ?? null;
}

/**
 * A circular-croppable flag image URL for a player's nationality, or
 * `null` when there's no usable mapping (missing nationality, or a value
 * this table doesn't recognize — e.g. API-Football's own "Unknown").
 * Callers must fall back to the existing initials avatar on `null`, and
 * should still treat a network/image-load failure for a non-null URL as
 * a fallback case too (see `PlayerAvatar`'s own `onError` handling) —
 * this function only answers "do we have a mapping," never "will this
 * URL definitely load."
 */
export function flagUrlForNationality(nationality: string | null | undefined): string | null {
  const code = flagCodeForNationality(nationality);
  return code ? `https://flagcdn.com/${code}.svg` : null;
}
