import type { Metadata } from "next";
import { LegalPage } from "@/components/public/legal-page";
import { CONTACT_EMAIL, OPERATOR_LEGAL_NAME, SITE_NAME } from "@/lib/site-config";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: `How ${SITE_NAME} collects, uses, and protects your information.`,
  alternates: { canonical: "/privacy" },
};

export default function PrivacyPage() {
  return (
    <LegalPage
      title="Privacy Policy"
      lastUpdated="October 2026"
      intro={`This page describes what ${SITE_NAME} actually collects and why — written from an audit of the real application, not a generic template.`}
    >
      <h2>Who operates Eleven</h2>
      <p>
        {SITE_NAME} is operated by {OPERATOR_LEGAL_NAME}. For any privacy question, contact{" "}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
      </p>

      <h2>Information you provide</h2>
      <ul>
        <li>
          <strong>Account information</strong> — your email address and password, used to create
          and authenticate your account (handled by our authentication provider, Supabase; we do
          not see or store your plaintext password ourselves).
        </li>
        <li>
          <strong>Profile information</strong> — a display name, and optionally an avatar image
          URL, shown to other managers in your leagues.
        </li>
        <li>
          <strong>Contact communications</strong> — anything you send us at{" "}
          {CONTACT_EMAIL}, kept for as long as reasonably needed to respond and maintain a
          record of the exchange.
        </li>
      </ul>

      <h2>Information generated by using Eleven</h2>
      <ul>
        <li>
          <strong>League and team activity</strong> — the leagues you join, your team name, your
          draft picks, your roster, and your lineup selections. This is the core data a fantasy
          platform needs to function, and other managers in your league can see league-scoped
          parts of it (e.g., your team name, roster, and draft picks) as part of normal gameplay.
        </li>
        <li>
          <strong>Authentication/session data</strong> — necessary session cookies set by
          Supabase (our authentication provider) that keep you signed in. See our{" "}
          <a href="/cookies">Cookies &amp; Storage</a> page for the full, specific list.
        </li>
        <li>
          <strong>Infrastructure logs</strong> — our hosting and database providers generate
          standard operational logs (e.g., request timestamps, IP addresses, error logs) as a
          normal part of running a web service. We use these for security and debugging, not for
          profiling or advertising.
        </li>
      </ul>

      <h2>What we do not currently do</h2>
      <p>
        As of this writing, {SITE_NAME} does not use third-party analytics, advertising, or
        marketing-tracking technology of any kind. We have audited the application&rsquo;s actual
        code and found no such integration. If that changes in the future, this page — and, if
        legally required, a consent mechanism — will be updated before it does, not after.
      </p>

      <h2>Necessary vs. optional technology</h2>
      <p>
        Every piece of browser storage {SITE_NAME} currently uses is strictly necessary for
        authentication and basic operation — there is no optional analytics or marketing
        technology to opt in or out of today. See{" "}
        <a href="/cookies">Cookies &amp; Storage</a> for specifics.
      </p>

      <h2>Third-party service providers</h2>
      <p>
        We use Supabase for authentication, database, and session management, and a hosting
        provider to run the application itself. We use a third-party football-data provider for
        real football statistics (see <a href="/data-sources">Data Sources</a>) — that provider
        does not receive your account information; we only send it requests for public football
        data.
      </p>

      <h2>Data retention</h2>
      <p>
        We retain account and league data for as long as your account remains active, so your
        leagues, rosters, and history stay intact. We have not yet finalized a specific
        deletion/retention timeline for closed accounts — treat this as a known gap rather than
        an invented number (see the human-review note below).
      </p>

      <h2>Your choices</h2>
      <p>
        You can update your display name and profile information from within {SITE_NAME}. To
        request deletion of your account and associated data, contact us at{" "}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
      </p>

      <h2>Changes to this policy</h2>
      <p>
        We may update this policy as {SITE_NAME} evolves. We&rsquo;ll update the &ldquo;Last
        updated&rdquo; date above when we do.
      </p>

      <h2>A note on legal review</h2>
      <p>
        This page reflects an honest audit of what {SITE_NAME} actually does today. It is not a
        substitute for legal advice, and it does not address jurisdiction-specific obligations
        (for example, GDPR or CCPA-specific rights language) that a human legal review should
        confirm before a broad public launch — see <a href="/disclaimer">Disclaimer</a>.
      </p>
    </LegalPage>
  );
}
